Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.7/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
from IPython.display import display
column_names = ['KW', 'Thema', 'Einheit', 'Commands']
events = [
    [41, 'Einleitung', 'Konzepte (Open Code, Open Data), Organisatorisches', 'NA'],
    [42, 'Command line', 'EinfÃ¼hrung', 'NA'],
    [43, 'Command line', ['cd', 'ls', 'touch']],
    [44, 'Git', 'EinfÃ¼hrung: Git, GitHub, GitLab, GitHub Education Pack', ['git config']],
    [45, 'Git', 'Basics', ['git init', 'git clone', 'git status', 'git add', 'git commit', 'git diff', 'git log']],
    [46, 'Git', 'Undoing changes', ['git reset',]],
    [47, 'Git', 'Branches', ['git branch', 'git checkout', 'git merge']],
    [48, 'Git', 'Kollaboration (GitHub, GitLab), Merge Conflicts', ['git remote', 'git push', 'git pull', 'git fetch']],
    [49, 'DataLad', 'EinfÃ¼hrung: DataLad', 'NA'],
    [50, 'DataLad', 'Basics', ['clone', 'install', 'save'] ],
    [51, 'DataLad', 'NA', 'NA'],
    [52, 'Weihnachtsferien', 'NA', 'NA'],
    [1, 'Weihnachtsferien', 'NA', 'NA'],
    [2, 'DataLad', 'NA', 'NA'],
    [3, 'DataLad', 'NA', 'NA'],
    [4, 'Abschluss', 'NA', 'NA'],
]
df_events = pd.DataFrame(events, columns=column_names)
display(df_events,  )
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn [1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mIPython[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdisplay[39;00m [38;5;28;01mimport[39;00m display
[1;32m      3[0m column_names [38;5;241m=[39m [[38;5;124m'[39m[38;5;124mKW[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mThema[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mEinheit[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mCommands[39m[38;5;124m'[39m]

[0;31mModuleNotFoundError[0m: No module named 'pandas'
ModuleNotFoundError: No module named 'pandas'

